Update utils.js
bitcoinjs/coinselect pull request #63
Opened 2021-04-13 14:29 UTC by Turtus

for anyone who do need segwit inputs actualized https://github.com/bitcoinjs/coinselect/issues/56

2021-09-11 01:02 UTC, jaonoctus requested changes

2021-09-11 01:02 UTC, jaonoctus commented on utils.js
> +var TX_INPUT_SEGWIT = 34
@Turtus Why 34?

btw, a transaction input will always have at least 41 bytes (`TX_INPUT_BASE = 32 + 4 + 1 + 4`).

- 32 bytes for the [previous txid hash](https://learnmeabitcoin.com/technical/txid)
- 4 bytes for the ([vout](https://learnmeabitcoin.com/technical/vout))
- 1 byte for the scriptSigSize [varint](https://learnmeabitcoin.com/technical/varint)
- 4 bytes for the sequence

https://learnmeabitcoin.com/technical/input

2021-09-11 01:08 UTC, jaonoctus commented
The best option for this workaround seems to be **not change anything on the algo**, and add for each P2WPKH (native segwit singlesig) input and output, `script.length = 27` instead.

```
function inputBytes (input) {
  if (typeof input.isSegwit !== 'undefined' && input.isSegwit) return TX_INPUT_SEGWIT;
  return TX_INPUT_BASE + (input.script ? input.script.length : TX_INPUT_PUBKEYHASH)
}

function outputBytes (output) {
  return TX_OUTPUT_BASE + (output.script ? output.script.length : TX_OUTPUT_PUBKEYHASH)
}
```

I'm not sure about P2WSH (multisig) or P2TR (taproot) tho 🤔

2021-09-13 07:52 UTC, Turtus commented
dno problem - ive already using script "with predefined" length not to patch the lib, but actual version is sooo not supporting segwit that anything will be improvement)

2021-09-13 07:52 UTC, closed without merging

2021-09-13 12:59 UTC, jaonoctus commented
@Turtus which script is that?

I agree :P

2021-09-14 14:32 UTC, Overtorment commented
fyi, this is how its approached in bluewallet: https://github.com/BlueWallet/BlueWallet/pull/3810