feat: add declaration file to prevent type error
bitcoinjs/coinselect pull request #77
Opened 2023-02-14 02:37 UTC by Hyunhum

I know it's pure js project, but a lot of typescript dev utilizes this module to optimize UTXO selection for bitcoin transaction. Just adding simple declaration file will make this library much more usable for typescript dev!

2023-08-09 09:55 UTC, Overtorment requested changes

2023-08-09 09:55 UTC, Overtorment commented on index.d.ts
> +    value: number
`value`  should be optional (in this case, library assings all remaining funds to this target)

2023-08-09 09:55 UTC, Overtorment commented on index.d.ts
> +    outputs: Target[],
inputs & outputs are optional, this means lib failed to satisfy the conditions

2023-08-10 10:10 UTC, ChrisCho-H commented
Thx, I updated following your suggestion.

2023-08-11 11:27 UTC, Overtorment approved these changes
![image](https://github.com/bitcoinjs/coinselect/assets/1913337/a3fea18b-712e-46b1-be1f-ebb5a6d9fbfc)
![image](https://github.com/bitcoinjs/coinselect/assets/1913337/09ba40e6-5eaa-4bd5-afba-e80dc4772b27)

2023-08-11 15:54 UTC, junderw commented
@Overtorment I gave you write permissions. Also, what is your npm user name?

2023-08-11 15:54 UTC, junderw approved these changes
Defer to @Overtorment

2023-08-11 15:57 UTC, LeeKorbisCa commented
Thank you everyone for getting this in :heart:

2023-08-11 18:11 UTC, junderw commented
... shouldn't this d.ts file be referenced in package.json?

2023-08-11 23:23 UTC, LeeKorbisCa commented
Yes, in the types property, as you probably read.

2023-08-12 01:13 UTC, ChrisCho-H commented
add types in package.json in 683e6dfae46795568172a4287260ce516b38eb7b

2023-08-12 02:15 UTC, junderw commented
@Overtorment merge when ready.

2023-08-13 18:27 UTC, merged

2023-08-13 18:27 UTC, Overtorment commented
@junderw i dont have npm account. dont trust them

2023-08-23 03:45 UTC, ChrisCho-H commented
I made PR https://github.com/bitcoinjs/coinselect/pull/82 to calculate fee more precisely(varying on type of input/output), which also adds `script` field type for UTXO and Target(coinselect accepts script as input and output. I should have added in this PR actually), and `isTaproot` field type for UTXO to calculate p2tr input bytes.

2023-09-22 10:12 UTC, griga commented
So this type declarations won't be published to npm ?

2023-09-26 02:21 UTC, ChrisCho-H commented
@griga If u need typed one in npm u can use [my forked version](https://github.com/ChrisCho-H/bitcoinselect). It also supports segwit fee calculation.